import { SymbolKind } from 'vscode';

interface SymbolInfo {
  pattern: RegExp;
  kind: SymbolKind;
  parent_kind?: SymbolKind;
  node_name: string;
  category_name: string;
  parent_name?: string;
  detail: string;
  item_pattern: RegExp;
}

export const symbolsInfo: Record<string, SymbolInfo> = {
  command: {
    pattern: /^(?!\\s)[0-9a-zA-Z\\-]+(?:(#|>))(?!.*(#|>|\s)$)/i,
    kind: SymbolKind.String,
    parent_kind: SymbolKind.Event,
    node_name: 'command',
    category_name: 'command',
    detail: 'command',
    item_pattern: /.*$/,
  },
  ip_vrf: {
    pattern: /^(?:\s|\t)*ip\svrf(?!\sforwarding)(?:\s)/i,
    kind: SymbolKind.Field,
    node_name: 'ip_vrf',
    category_name: 'routing',
    detail: 'ip vrf',
    item_pattern: /.*$/,
  },
  router_bgp: {
    pattern: /^(?:\s|\t)*router\sbgp(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'router_bgp',
    category_name: 'routing',
    detail: 'router bgp',
    item_pattern: /\d*$/,
  },
  router_ospf: {
    pattern: /^(?:\s|\t)*router\sospf(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'router_ospf',
    category_name: 'routing',
    detail: 'router ospf',
    item_pattern: /\d*$/,
  },
  router_eigrp: {
    pattern: /^(?:\s|\t)*router\seigrp(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'router_eigrp',
    category_name: 'routing',
    detail: 'router eigrp',
    item_pattern: /\d*$/,
  },
  router_rip: {
    pattern: /^(?:\s|\t)*router\srip(?:\s|$)/i,
    kind: SymbolKind.Class,
    node_name: 'router_rip',
    category_name: 'routing',
    detail: 'router rip',
    item_pattern: /.*$/,
  },
  router_isis: {
    pattern: /^(?:\s|\t)*router\sisis(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'router_isis',
    category_name: 'routing',
    detail: 'router isis',
    item_pattern: /\d*$/,
  },
  address_family: {
    pattern: /^(?:\s|\t)*(address-family)(?:\s)/i,
    kind: SymbolKind.Field,
    node_name: 'address_family',
    category_name: 'routing',
    parent_name: '.*',
    detail: 'address-family',
    item_pattern: /.*$/,
  },
  class_map: {
    pattern: /^(?:\s|\t)*(class-map)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'class_map',
    category_name: 'qos',
    detail: 'class-map',
    item_pattern: /.*$/,
  },
  policy_map: {
    pattern: /^(?:\s|\t)*(policy-map)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'policy_map',
    category_name: 'qos',
    detail: 'policy-map',
    item_pattern: /.*$/,
  },
  service_policy: {
    pattern: /^(?:\s|\t)*(service-policy)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'service_policy',
    category_name: 'qos',
    detail: 'service-policy',
    item_pattern: /.*$/,
  },
  interface: {
    pattern: /^(?:\s|\t)*(interface)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'interface',
    category_name: 'interface',
    detail: 'interface',
    item_pattern: /[^.]*$/,
  },
  interface_range: {
    pattern: /^(?:\s|\t)*(interface)\s+(range)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'interface_range',
    category_name: 'interface',
    detail: 'interface range',
    item_pattern: /.*$/,
  },
  sub_interface: {
    pattern: /^(?:\s|\t)*(interface)(?:\s)/i,
    kind: SymbolKind.Interface,
    node_name: 'interface',
    category_name: 'interface',
    parent_name: '.+.',
    detail: 'sub-interface',
    item_pattern: /.*\..*$/,
  },
  ip_access_list: {
    pattern: /^(?:\s|\t)*(ip)\s+(access-list)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'ip_access_list',
    category_name: 'acl',
    detail: 'ip access-list',
    item_pattern: /.*$/,
  },
  ipv6_access_list: {
    pattern: /^(?:\s|\t)*(ipv6)\s+(access-list)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'ipv6_access_list',
    category_name: 'acl',
    detail: 'ipv6 access-list',
    item_pattern: /.*$/,
  },
  access_list: {
    pattern: /^(?:\s|\t)*(access-list)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'access_list',
    category_name: 'acl',
    detail: 'access-list',
    item_pattern: /.*$/,
  },
  crypto_map: {
    pattern: /^(?:\s|\t)*(crypto)\s+(map)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'crypto_map',
    category_name: 'security',
    detail: 'crypto map',
    item_pattern: /.*$/,
  },
  crypto_isakmp: {
    pattern: /^(?:\s|\t)*(crypto)\s+(isakmp)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'crypto_isakmp',
    category_name: 'security',
    detail: 'crypto isakmp',
    item_pattern: /.*$/,
  },
  crypto_ikev2: {
    pattern: /^(?:\s|\t)*(crypto)\s+(ikev2)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'crypto_ikev2',
    category_name: 'security',
    detail: 'crypto ikev2',
    item_pattern: /.*$/,
  },
  ipsec_profile: {
    pattern: /^(?:\s|\t)*(ipsec)\s+(profile)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'ipsec_profile',
    category_name: 'security',
    detail: 'ipsec profile',
    item_pattern: /.*$/,
  },
  keyring: {
    pattern: /^(?:\s|\t)*(keyring)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'keyring',
    category_name: 'security',
    detail: 'keyring',
    item_pattern: /.*$/,
  },
  aaa_authentication: {
    pattern: /^(?:\s|\t)*(aaa)\s+(authentication)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'aaa_authentication',
    category_name: 'security',
    detail: 'aaa authentication',
    item_pattern: /.*$/,
  },
  aaa_authorization: {
    pattern: /^(?:\s|\t)*(aaa)\s+(authorization)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'aaa_authorization',
    category_name: 'security',
    detail: 'aaa authorization',
    item_pattern: /.*$/,
  },
  aaa_accounting: {
    pattern: /^(?:\s|\t)*(aaa)\s+(accounting)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'aaa_accounting',
    category_name: 'security',
    detail: 'aaa accounting',
    item_pattern: /.*$/,
  },
  line_vty: {
    pattern: /^(?:\s|\t)*(line)\s+(vty)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'line_vty',
    category_name: 'line',
    detail: 'line vty',
    item_pattern: /.*$/,
  },
  line_con: {
    pattern: /^(?:\s|\t)*(line)\s+(con(?:sole)?)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'line_con',
    category_name: 'line',
    detail: 'line con',
    item_pattern: /.*$/,
  },
  line_aux: {
    pattern: /^(?:\s|\t)*(line)\s+(aux)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'line_aux',
    category_name: 'line',
    detail: 'line aux',
    item_pattern: /.*$/,
  },
  username: {
    pattern: /^(?:\s|\t)*(username)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'username',
    category_name: 'security',
    detail: 'username',
    item_pattern: /.*$/,
  },
  vlan: {
    pattern: /^(?:\s|\t)*(vlan)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'vlan',
    category_name: 'layer2',
    detail: 'vlan',
    item_pattern: /\d*$/,
  },
  spanning_tree: {
    pattern: /^(?:\s|\t)*(spanning-tree)(?:\s)/i,
    kind: SymbolKind.Field,
    node_name: 'spanning_tree',
    category_name: 'layer2',
    detail: 'spanning-tree',
    item_pattern: /.*$/,
  },
  switchport: {
    pattern: /^(?:\s|\t)*(switchport)(?:\s)/i,
    kind: SymbolKind.Field,
    node_name: 'switchport',
    category_name: 'layer2',
    detail: 'switchport',
    item_pattern: /.*$/,
  },
  snmp_server: {
    pattern: /^(?:\s|\t)*(snmp-server)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'snmp_server',
    category_name: 'services',
    detail: 'snmp-server',
    item_pattern: /.*$/,
  },
  logging: {
    pattern: /^(?:\s|\t)*(logging)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'logging',
    category_name: 'services',
    detail: 'logging',
    item_pattern: /.*$/,
  },
  ntp: {
    pattern: /^(?:\s|\t)*(ntp)(?:\s)/i,
    kind: SymbolKind.Variable,
    node_name: 'ntp',
    category_name: 'services',
    detail: 'ntp',
    item_pattern: /.*$/,
  },
  ip_dhcp_pool: {
    pattern: /^(?:\s|\t)*(ip)\s+(dhcp)\s+(pool)(?:\s)/i,
    kind: SymbolKind.Class,
    node_name: 'ip_dhcp_pool',
    category_name: 'services',
    detail: 'ip dhcp pool',
    item_pattern: /.*$/,
  },
};
